/**
 * Extended error directory entries, part 2.
 *
 * Database, HTTP/API, security and data-integrity failure modes. Combined with
 * `error-catalog-extended.ts` and the base directory into one `ERROR_CATALOG`.
 */

import type { ErrorCatalogEntry } from "./error-catalog";

export const EXTENDED_ERROR_CATALOG_2: ErrorCatalogEntry[] = [
  // ----------------------------------------------------------------- database
  {
    id: "replication-lag",
    title: "Replication lag / stale replica reads",
    category: "database",
    severity: "warning",
    languages: ["sql", "mysql", "postgres", "mongodb", "dynamodb"],
    patterns: [
      /replication lag/i,
      /replica (?:is )?(?:behind|stale|lagging)/i,
      /read ?after ?write/i,
      /eventual(?:ly)? consistent/i,
      /follower (?:is )?behind/i,
      /slave (?:is )?behind/i,
    ],
    reasons: [
      "A read went to a replica before the write was applied there, so the user sees stale data.",
      "One replica fell behind (slow disk, long transaction) and is still serving reads.",
      "The application reads-after-write without pinning the session to the primary.",
    ],
    fixes: [
      "Route reads that must see their own writes to the primary, or add a short consistency wait.",
      "Alert on replication lag; a lagging replica serving reads is a data-correctness incident.",
      "Identify lagging replicas and drain them instead of letting them answer.",
    ],
  },
  {
    id: "connection-dropped",
    title: "Database connection dropped mid-query",
    category: "database",
    severity: "critical",
    languages: ["sql", "mysql", "postgres", "mongodb"],
    patterns: [
      /connection (?:was )?(?:closed|reset|dropped|terminated)/i,
      /server has gone away/i,
      /broken (?:mysql )?connection/i,
      /connection reset by peer/i,
      /no connection to the server/i,
      /socket (?:exception )?on (?:read|write)/i,
    ],
    reasons: [
      "The database restarted, failed over or was killed by the platform mid-transaction.",
      "A firewall or idle-timeout closed a long-idle pooled connection that was handed out later.",
      "The server closed the connection because a statement ran past `wait_timeout` or a proxy limit.",
    ],
    fixes: [
      "Set a validation query on borrowed connections so a dead socket is detected before use.",
      "Make the transaction retryable and idempotent; the outcome of a dropped connection is unknown.",
      "Keep the pool below the server's `max_connections` so idle reaping never hits a busy client.",
    ],
  },
  {
    id: "transaction-rollback",
    title: "Transaction rolled back / aborted",
    category: "database",
    severity: "warning",
    languages: ["sql", "postgres", "mysql", "mongodb"],
    patterns: [
      /transaction (?:was )?(?:rolled back|aborted|cancelled)/i,
      /rollback(?:ed)?(?: due to| because)/i,
      /current transaction is aborted/i,
      /savepoint/i,
      /atomicity violation/i,
    ],
    reasons: [
      "One statement failed, and the code continued issuing statements in the same broken transaction.",
      "The transaction was rolled back but the code still reported success to the caller.",
      "A deadlock or serialization failure aborted the transaction and it was not retried.",
    ],
    fixes: [
      "Roll back in a `finally`/catch on every exit path and re-throw a meaningful error.",
      "Retry serialization failures and deadlocks at the transaction boundary, not per statement.",
      "Never acknowledge work whose transaction was rolled back — check the commit result.",
    ],
  },
  {
    id: "db-migration",
    title: "Schema migration mismatch",
    category: "database",
    severity: "critical",
    languages: ["sql", "flyway", "liquibase", "prisma", "django"],
    patterns: [
      /relation "?\w+"? does not exist/i,
      /column .* does not exist/i,
      /unknown column/i,
      /migration (?:failed|checksum mismatch|not applied)/i,
      /table .* (?:already exists|not found)/i,
      /flyway|liquibase/i,
    ],
    reasons: [
      "The application was deployed before its migration ran, or the migration ran against another database.",
      "A migration was edited after it had been applied, so its checksum no longer matches.",
      "The service connects to a replica that has not been migrated yet.",
    ],
    fixes: [
      "Run migrations as a deploy step that must succeed before the new version starts.",
      "Never edit an applied migration — add a new one; make the checksum mismatch fail the deploy.",
      "Verify the connection string targets the primary, not a read replica.",
    ],
  },
  {
    id: "query-plan-regression",
    title: "Slow query / missing index",
    category: "database",
    severity: "warning",
    languages: ["sql", "any"],
    patterns: [
      /slow query/i,
      /query (?:took|exceeded) \d{3,}/i,
      /execution plan/i,
      /seq scan|sequential scan/i,
      /using filesort|using temporary/i,
      /index (?:is )?(?:missing|not used|unused)/i,
    ],
    reasons: [
      "A new predicate was added on an unindexed column, so the plan flipped to a full table scan.",
      "Statistics are stale after a bulk load, so the planner picks a bad plan.",
      "A query now runs inside a loop (N+1) and the per-call cost was never a problem on its own.",
    ],
    fixes: [
      "Capture the plan with `EXPLAIN (ANALYZE, BUFFERS)` and index the columns used in filters and joins.",
      "Refresh statistics after large data changes and pin plans only as a last resort.",
      "Detect N+1 patterns in the application layer; the database sees many cheap queries, not one slow one.",
    ],
  },

  // ----------------------------------------------------------------- http-api
  {
    id: "payload-too-large",
    title: "Payload too large",
    category: "http-api",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /payload too large/i,
      /request entity too large/i,
      /(?:status(?:_?code)?|responded with)\D{0,14}413\b/i,
      /" 413(?: |$)/,
      /request body.*exceeds/i,
      /maximum (?:upload|request) size/i,
      /body size .* limit/i,
    ],
    reasons: [
      "A bulk upload or export exceeded the server's body limit.",
      "The limit was raised on the gateway but not on the service, or vice versa.",
      "A retry replayed a body that had grown in the meantime.",
    ],
    fixes: [
      "Align body limits across gateway, proxy and service, and document the real maximum.",
      "Chunk large uploads, and return the limit in the error message so the client can adapt.",
      "Reject on declared content-length before reading the body.",
    ],
  },
  {
    id: "validation-error",
    title: "Input validation failure",
    category: "http-api",
    severity: "info",
    languages: ["any"],
    patterns: [
      /validation (?:failed|error)/i,
      /invalid (?:request|parameter|argument|payload)/i,
      // A bare 400 also appears in timestamps (`10:00:12,400`), so the status
      // has to arrive with context.
      /(?:status(?:_?code)?|responded with|responde?d)\D{0,14}400\b/i,
      /" 400(?: |$)/,
      /missing required (?:field|parameter)/i,
      /does not match the (?:required )?pattern/i,
      /failed to (?:convert|parse) (?:request|parameter)/i,
    ],
    reasons: [
      "The client sends a value outside the documented range, or omits a required field.",
      "A field was renamed or made optional without updating the client.",
      "A validation rule is stricter than the contract the client was written against.",
    ],
    fixes: [
      "Return the exact field, expected shape and received value in the error body.",
      "Generate the client and server schema from one definition so drift fails in CI.",
      "Separate genuine client bugs from expected validation noise in the error budget.",
    ],
  },
  {
    id: "unsupported-media",
    title: "Unsupported media type / encoding",
    category: "http-api",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /unsupported media type/i,
      /(?:status(?:_?code)?|responded with)\D{0,14}415\b/i,
      /" 415(?: |$)/,
      /content[- ]type .* (?:not supported|unsupported)/i,
      /unsupported ?charset/i,
      /cannot (?:decode|parse) content[- ]?type/i,
      /malformed multipart/i,
    ],
    reasons: [
      "The client sends a different content type than the endpoint declares (json vs form vs xml).",
      "A proxy re-encoded the body and lost the charset or the boundary of a multipart upload.",
      "The endpoint dropped support for a format that clients still use.",
    ],
    fixes: [
      "Advertise the accepted types in the error response and validate before reading the body.",
      "Pin the charset in the content type and configure proxies not to rewrite it.",
      "Return 415 during rollout for old formats instead of parsing and failing later.",
    ],
  },
  {
    id: "gateway-timeout",
    title: "Gateway timeout / request deadline exceeded",
    category: "http-api",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /(?:status(?:_?code)?|responded with)\D{0,14}504\b/i,
      /" 504(?: |$)/,
      /gateway time-?out/i,
      /upstream timed out/i,
      /deadline exceeded/i,
      /request timed out.*proxy/i,
      /no healthy upstream/i,
    ],
    reasons: [
      "The service took longer than the proxy's timeout, so the client got a 504 although the work continued.",
      "One dependency in the request path is slow, and every hop waits for it.",
      "The server is saturated and queued requests exceed the deadline before they even start.",
    ],
    fixes: [
      "Set a deadline that propagates inwards so the work stops when the client has already given up.",
      "Find the slowest hop (see the latency section) and fix it rather than raising every timeout.",
      "Return a fast, honest error and make the operation idempotent so a client retry is safe.",
    ],
  },
  {
    id: "not-implemented",
    title: "Not implemented / unsupported operation",
    category: "http-api",
    severity: "info",
    languages: ["any"],
    patterns: [
      /not implemented/i,
      /(?:status(?:_?code)?|responded with)\D{0,14}501\b/i,
      /" 501(?: |$)/,
      /unsupported operation/i,
      /todo:? /i,
      /unimplemented/i,
      /this endpoint is a stub/i,
    ],
    reasons: [
      "A stub or placeholder handler was left in the code path and is now reachable by a client.",
      "The method was removed during an API cleanup but the route still answers.",
      "A feature flag that gates the real implementation is off in this environment.",
    ],
    fixes: [
      "Return a clear 501 with a link to the supported alternatives, or remove the route.",
      "Fail the build on TODO markers in handler code.",
      "Log the caller (service, version, api key id) so the traffic can be redirected.",
    ],
  },
  {
    id: "cors",
    title: "CORS / preflight rejection",
    category: "http-api",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /cors/i,
      /access-control-allow-origin/i,
      /preflight/i,
      /blocked by cors policy/i,
      /origin .* not allowed/i,
    ],
    reasons: [
      "The allowed origin list does not include the calling environment (preview URL, staging, mobile webview).",
      "The response omits the headers for the actual method/header, so the browser blocks a safe request.",
      "A proxy strips the CORS headers on the way back.",
    ],
    fixes: [
      "Keep one explicit origin allowlist per environment and never reflect an arbitrary origin.",
      "Echo the request's `Access-Control-Request-Headers` and allow only the headers the API uses.",
      "Verify headers after the proxy hop, not before it.",
    ],
  },

  // ----------------------------------------------------------------- security
  {
    id: "path-traversal",
    title: "Path traversal attempt",
    category: "security",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /path traversal/i,
      /\.\.\//,
      /directory traversal/i,
      /outside the (?:allowed )?(?:root|base) ?(?:dir|directory)/i,
      /invalid file path.*\.\./i,
    ],
    reasons: [
      "A request tried to escape the intended directory with `../` or an absolute path.",
      "A user-supplied filename is concatenated into a path without normalisation.",
      "Symlinks inside the served directory point outside it.",
    ],
    fixes: [
      "Resolve the path and verify it is inside the allowed root before opening it.",
      "Never accept a path from the client at all — accept an id and look the path up.",
      "Serve uploads from a separate origin and encode filenames so they cannot contain separators.",
    ],
  },
  {
    id: "ssrf",
    title: "Server-side request forgery",
    category: "security",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /ssrf/i,
      /server-side request forgery/i,
      /blocked (?:private|internal|metadata) (?:address|url|host)/i,
      /169\.254\.169\.254/i,
      /request to (?:internal|private) (?:host|address) blocked/i,
    ],
    reasons: [
      "The service fetches a user-supplied url and reaches the cloud metadata endpoint or an internal service.",
      "The url is validated by string prefix only, so `http://internal/` or a redirect bypasses it.",
      "DNS rebinding resolves to an internal address after validation.",
    ],
    fixes: [
      "Resolve the host and reject private, loopback, link-local and metadata ranges after resolution.",
      "Use a fixed allowlist of outbound destinations, and disable redirects on server-side fetches.",
      "Require an egress proxy so the application itself has no route to internal networks.",
    ],
  },
  {
    id: "weak-crypto",
    title: "Weak or disallowed cryptography",
    category: "security",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /weak (?:cipher|algorithm|hash)/i,
      /insecure (?:cipher|algorithm)/i,
      /md5|sha1/i,
      /des\b|rc4\b|ecb mode/i,
      /disabled (?:cipher|protocol)/i,
      /no cipher suites in common/i,
    ],
    reasons: [
      "A legacy algorithm is still used for compatibility and now trips a scanner or a hardened peer.",
      "A default was never changed when the requirement tightened.",
      "A library upgrade removed or disabled the algorithm that the code asks for.",
    ],
    fixes: [
      "Move to an authenticated cipher and a modern hash, with a migration path for stored data.",
      "Pin the algorithm in one place so it can be rotated without touching call sites.",
      "Set the security level explicitly in the runtime and container image so defaults cannot drift.",
    ],
  },
  {
    id: "insecure-transport",
    title: "Plaintext credential transport",
    category: "security",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /insecure (?:transport|connection)/i,
      /plain ?text (?:connection|password|credential)/i,
      /credentials sent in plain/i,
      /http:\/\/.*(?:login|auth|token)/i,
      /no tls|no ssl.*internal/i,
    ],
    reasons: [
      "An internal service is called over http because it is 'inside the network'.",
      "A redirect downgraded https, or a client was configured with verification disabled.",
      "A webhook or callback url was configured with http by mistake.",
    ],
    fixes: [
      "Require https everywhere, including service-to-service traffic, and reject http at the edge.",
      "Enforce mTLS where the threat model needs it.",
      "Rotate any credential that was transmitted in plaintext.",
    ],
  },
  {
    id: "log-injection",
    title: "Log forging / control characters",
    category: "security",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /log injection/i,
      /log forging/i,
      /crlf (?:in|injection)/i,
      /newline in (?:header|parameter|value)/i,
      /null byte in/i,
    ],
    reasons: [
      "User input containing newlines is written to the log, forging extra log entries.",
      "A control character breaks a log parser or a single-line log format downstream.",
      "A header value was used unvalidated, enabling response splitting.",
    ],
    fixes: [
      "Escape newlines and control characters at the logging boundary, or use structured fields.",
      "Reject control characters in input at validation time.",
      "Parse logs as structured records so a forged line cannot masquerade as a real one.",
    ],
  },

  // ----------------------------------------------------------- data integrity
  {
    id: "data-loss",
    title: "Data loss / missing records",
    category: "data-integrity",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /data loss/i,
      /(?:records?|rows?|documents?|messages?) (?:were |was )?(?:lost|dropped|deleted|missing)/i,
      /expected \d+ .*(?:got|found) \d+/i,
      /count mismatch/i,
      /missing (?:records?|rows?|documents?|keys?)/i,
      /silent(?:ly)? (?:lost|dropped)/i,
    ],
    reasons: [
      "A batch job acknowledged a partial write, so the unprocessed part was never retried.",
      "A consumer offset was committed before the work was durable.",
      "A hard kill happened between the read and the write with no transaction to recover the gap.",
    ],
    fixes: [
      "Commit offsets and messages only after the side effect is durable.",
      "Reconcile counts on both sides (read and written) and alert on any difference.",
      "Make batch processing resumable from a checkpoint instead of restarting from the beginning.",
    ],
  },
  {
    id: "numeric-precision",
    title: "Floating-point / rounding error",
    category: "data-integrity",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /floating ?point/i,
      /rounding error/i,
      /decimal ?(?:mismatch|overflow)/i,
      /precision (?:loss|error)/i,
      /binary ?float/i,
      /bigdecimal/i,
    ],
    reasons: [
      "Money or quantities are stored in a float/double, where 0.1 + 0.2 is not 0.3.",
      "Values were converted through a string in a locale-dependent way.",
      "A unit conversion introduced a small error that accumulated over many rows.",
    ],
    fixes: [
      "Use a fixed-point decimal type for money and quantities, and round only at the boundary.",
      "Keep units explicit in names and do conversions once, at the edge.",
      "Add a test asserting exact sums for a known set of values.",
    ],
  },
  {
    id: "state-machine",
    title: "Invalid state transition",
    category: "data-integrity",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /invalid (?:state|status) transition/i,
      /cannot (?:transition|move).*to status/i,
      /unexpected status/i,
      /illegal state/i,
      /transition .* not allowed/i,
      /already (?:completed|cancelled|shipped|closed)/i,
    ],
    reasons: [
      "Two actors raced over the same entity (user cancels while the worker ships).",
      "A webhook arrived twice and re-applied a transition that is only valid once.",
      "The state machine allows a transition in the API but the worker does not implement it.",
    ],
    fixes: [
      "Make the transition conditional on the current state so a race cannot double-apply it.",
      "Define the state machine once and generate both the API validation and the worker logic from it.",
      "Treat duplicate terminal transitions as success, not as errors.",
    ],
  },
];