/**
 * Extended error directory entries, part 3.
 *
 * The newer categories: queueing and backpressure, caching, external services,
 * container runtime, business rules, encoding/locale and scheduling. Combined
 * with the other catalog files into one `ERROR_CATALOG`.
 */

import type { ErrorCatalogEntry } from "./error-catalog";

export const EXTENDED_ERROR_CATALOG_3: ErrorCatalogEntry[] = [
  // --------------------------------------------------- queues and backpressure
  {
    id: "queue-unavailable",
    title: "Message broker unavailable",
    category: "queue-backlog",
    severity: "critical",
    languages: ["kafka", "rabbitmq", "sqs", "node", "java", "python"],
    patterns: [
      /broker (?:is )?(?:not )?(?:available|unreachable|down)/i,
      /(?:kafka|rabbitmq|activemq)[^\n]*?(?:connection refused|timed out)/i,
      /no brokers available/i,
      /queue (?:is )?(?:unavailable|unreachable)/i,
      /topic (?:not found|does not exist|unavailable)/i,
      /503 service unavailable.*(?:broker|queue|mq)/i,
    ],
    reasons: [
      "The broker is down, restarting, or a rolling deploy removed the leader.",
      "Credentials or the SASL/TLS configuration differ from what the cluster expects.",
      "A network policy change blocks the broker port from this workload.",
    ],
    fixes: [
      "Retry with backoff and keep publishing locally (outbox) so a broker outage does not lose events.",
      "Monitor broker connectivity per client so a silent partition is visible immediately.",
      "Verify credentials and TLS material at startup rather than on the first publish.",
    ],
  },
  {
    id: "queue-full",
    title: "Queue full / rejected message",
    category: "queue-backlog",
    severity: "critical",
    languages: ["kafka", "rabbitmq", "sqs", "node", "java"],
    patterns: [
      /queue (?:is )?full/i,
      /queue (?:depth|length) (?:exceeded|is too)/i,
      /buffer (?:is )?full/i,
      /max.?len|overflow|overflowed/i,
      /message (?:was )?rejected/i,
      /publish.*failed.*(?:full|overflow)/i,
    ],
    reasons: [
      "Producers outrun consumers, so the backlog grows until the broker refuses writes.",
      "A consumer died and nobody noticed, so its partition stopped draining.",
      "A traffic spike (retry storm, duplicated event) flooded the topic.",
    ],
    fixes: [
      "Alert on consumer lag and on the oldest unprocessed message age, not on broker CPU.",
      "Add backpressure: slow producers down instead of dropping events.",
      "Make consumers idempotent so replaying after a restart is safe.",
    ],
  },
  {
    id: "consumer-lag",
    title: "Consumer lag / growing backlog",
    category: "queue-backlog",
    severity: "warning",
    languages: ["kafka", "rabbitmq", "sqs", "node", "java", "python"],
    patterns: [
      /consumer lag/i,
      /(?:group|consumer) (?:is )?(?:behind|lagging)/i,
      /offset (?:is )?behind/i,
      /backlog (?:is )?(?:growing|increasing)/i,
      /oldest (?:unprocessed|message)/i,
      /processing is falling behind/i,
    ],
    reasons: [
      "Each message takes longer than the arrival interval, so lag grows monotonically.",
      "One consumer was removed from the group and its partitions were rebalanced slowly.",
      "A downstream dependency slowed the consumer loop (see the latency section).",
    ],
    fixes: [
      "Scale consumers with the partition count; more consumers than partitions do nothing.",
      "Break up slow messages with a timeout instead of letting one block the partition.",
      "Track lag per partition to spot a single poisoned partition.",
    ],
  },
  {
    id: "poison-message",
    title: "Poison message / repeatedly failing job",
    category: "queue-backlog",
    severity: "warning",
    languages: ["kafka", "rabbitmq", "sqs", "node", "java", "python"],
    patterns: [
      /poison (?:message|pill)/i,
      /message (?:will be )?discarded/i,
      /max(?:imum)? (?:delivery|attempt|retry) (?:count )?exceeded/i,
      /dead[- ]letter/i,
      /\bdlq\b/i,
      /moving to (?:the )?dead/i,
      /retry (?:count|limit) (?:exceeded|reached)/i,
    ],
    reasons: [
      "One message is structurally invalid (bad encoding, missing field) and fails identically every time.",
      "The handler throws before it can record progress, so redelivery never helps.",
      "An idempotency guard makes the retry fail on the second attempt.",
    ],
    fixes: [
      "Park poison messages in a dead-letter queue with the reason and the original payload.",
      "Quarantine and alert on dead-letter growth instead of silently retrying forever.",
      "Make handlers idempotent by key so a retry succeeds on the second attempt.",
    ],
  },
  {
    id: "offset-reset",
    title: "Offset reset / out-of-order processing",
    category: "queue-backlog",
    severity: "warning",
    languages: ["kafka", "node", "java", "python"],
    patterns: [
      /offset (?:out of range|reset)/i,
      /reset(?:ting)? (?:the )?offset/i,
      /auto(?:commit)?\.offset\.reset/i,
      /no committed offset/i,
      /rebalance(?:ment)? (?:in progress|detected)/i,
      /partition (?:re)?assignment/i,
    ],
    reasons: [
      "The consumer group committed offsets that the broker already expired (retention window).",
      "A new consumer group started from the default `latest`, so history was skipped.",
      "A rebalance interrupted processing and the offsets were committed after the reassignment.",
    ],
    fixes: [
      "Choose and document the reset policy (earliest for replay, latest for new consumers).",
      "Commit offsets only after processing succeeds, and disable auto-commit.",
      "Alert when a reset happens — silently replayed or skipped partitions are a correctness risk.",
    ],
  },

  // ------------------------------------------------------------------ caching
  {
    id: "cache-stampede",
    title: "Cache stampede / thundering herd",
    category: "caching",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /cache stampede/i,
      /thundering herd/i,
      /cache dogpile/i,
      /cache miss (?:storm|spike|burst)/i,
      /many concurrent (?:cache )?misses/i,
    ],
    reasons: [
      "A popular key expired and every request for it queried the database at once.",
      "A deploy or flush emptied the cache while traffic was at its peak.",
      "There is no single-flight lock, so identical work runs in parallel.",
    ],
    fixes: [
      "Serve stale content while one request refreshes in the background (stale-while-revalidate).",
      "Add jitter to TTLs so a batch of keys does not expire together.",
      "Collapse concurrent misses for the same key with a per-key lock.",
    ],
  },
  {
    id: "cache-unavailable",
    title: "Cache unavailable / eviction pressure",
    category: "caching",
    severity: "warning",
    languages: ["redis", "memcached", "any"],
    patterns: [
      /cache (?:is )?(?:unavailable|down|unreachable)/i,
      /redis[^n]*connection (?:refused|reset)/i,
      /memcached/i,
      /evicted \d+ (?:keys|objects)/i,
      /maxmemory|oom command not allowed/i,
      /cache miss ratio/i,
    ],
    reasons: [
      "The cache node restarted or failed over and clients retried without backoff.",
      "The instance is full (`maxmemory`) and is evicting, so hit rate collapses.",
      "The client library reconnects on every call, adding latency to every request.",
    ],
    fixes: [
      "Treat the cache as optional: degrade to the origin instead of failing the request.",
      "Size the cache for the working set and set an explicit eviction policy.",
      "Warm critical keys after a restart, or keep them in a local in-process cache.",
    ],
  },
  {
    id: "stale-cache",
    title: "Stale cache entry",
    category: "caching",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /stale (?:cache|entry|value|data)/i,
      /cache (?:entry )?(?:is )?(?:outdated|expired)/i,
      /served from cache.*stale/i,
      /inconsistent read/i,
      /stale-?while-?revalidate/i,
    ],
    reasons: [
      "Invalidation is missing or asynchronous, so readers see the previous version.",
      "A multi-node cache is not invalidated everywhere after a write.",
      "A long TTL was chosen to protect hit rate and nobody revisited it.",
    ],
    fixes: [
      "Invalidate on write (or use a versioned key) rather than relying on TTL alone.",
      "Publish invalidation through the same event bus every node listens to.",
      "Make the TTL a deliberate, per-key decision and log the age of served entries.",
    ],
  },
  {
    id: "cache-penetration",
    title: "Cache penetration / negative caching",
    category: "caching",
    severity: "info",
    languages: ["any"],
    patterns: [
      /cache penetration/i,
      /negative cach/i,
      /lookup miss for (?:missing|nonexistent)/i,
      /repeated miss/i,
      /null (?:result )?cached/i,
    ],
    reasons: [
      "Requests for keys that do not exist are never cached, so every one hits the database.",
      "A scanner or a broken client generates random ids, all of them missing.",
      "Not-found results are cached as a real value, so a created object stays invisible.",
    ],
    fixes: [
      "Cache negative results briefly (short TTL) to absorb lookup storms.",
      "Return a distinct 404 that is cheap to serve, and rate-limit unknown-key lookups.",
      "Distinguish 'cached empty' from 'cached value' so writes invalidate correctly.",
    ],
  },

  // ------------------------------------------------------- external services
  {
    id: "third-party-api",
    title: "Third-party API failure",
    category: "external-services",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /upstream (?:api|service) (?:error|failed)/i,
      /api returned (?:5\d\d|http 5)/i,
      /bad response from/i,
      /unexpected response (?:from|body)/i,
      /vendor api/i,
      /third[- ]party (?:api|service) (?:error|failure)/i,
    ],
    reasons: [
      "The provider has an incident, or a partial outage in one region.",
      "The response changed shape (a field removed) and the client rejects it.",
      "The account hit a provider limit or its credentials were revoked.",
    ],
    fixes: [
      "Wrap every outbound call with a timeout, retry budget and a circuit breaker.",
      "Validate and log the response shape so a contract change is caught in staging.",
      "Keep a fallback path (cached value, queued retry) for anything user-visible.",
    ],
  },
  {
    id: "email-delivery",
    title: "Email / SMTP delivery failure",
    category: "external-services",
    severity: "warning",
    languages: ["java", "python", "node", "any"],
    patterns: [
      /smtp/i,
      /mail(?:gun|chimp|jet|slack)? (?:delivery|send) (?:failed|error)/i,
      /could not send (?:mail|email|message)/i,
      /550\b|552\b|553\b|421\b/,
      /message (?:rejected|deferred|bounced)/i,
      /undeliver(?:ed|able)/i,
    ],
    reasons: [
      "The recipient domain has no MX record, rejects the sender, or greylists the relay.",
      "SPF/DKIM/DMARC fail, so the provider treats the message as spam.",
      "Rate limits or a daily sending quota were hit.",
    ],
    fixes: [
      "Queue mail and retry with backoff instead of failing the user request.",
      "Authenticate the sending domain (SPF, DKIM, DMARC) before going to production.",
      "Handle hard bounces (5xx) as permanent and stop retrying; treat 4xx as temporary.",
    ],
  },
  {
    id: "object-storage",
    title: "Object storage failure",
    category: "external-services",
    severity: "warning",
    languages: ["s3", "gcs", "azure", "any"],
    patterns: [
      /s3|gcs|azure blob|minio|object storage/i,
      /bucket (?:does not exist|not found|access denied)/i,
      /no such bucket|nosuchkey/i,
      /upload failed|download failed.*(?:bucket|storage)/i,
      /presigned ?url (?:expired|invalid)/i,
      /signature does not match/i,
    ],
    reasons: [
      "Credentials lack permission for the bucket/prefix, or the key was rotated.",
      "A presigned url expired (or the clock on either side is skewed).",
      "The bucket is in another region and the call had to cross it on every request.",
    ],
    fixes: [
      "Fail fast at startup by writing and reading a probe object with the production credentials.",
      "Issue presigned urls with a sensible expiry and refresh them on the client side.",
      "Pin the region and configure a single endpoint to avoid cross-region latency.",
    ],
  },
  {
    id: "webhook-delivery",
    title: "Webhook delivery failure",
    category: "external-services",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /webhook (?:delivery|post|call) (?:failed|error)/i,
      /callback (?:failed|error|url)/i,
      /http (?:status )?[45]\d\d from subscriber/i,
      /subscriber (?:url )?(?:unreachable|rejected)/i,
      /delivery attempt \d+ failed/i,
    ],
    reasons: [
      "The subscriber is down, slow, or rejects requests from your IP range.",
      "The endpoint moved and still points at the old URL.",
      "Your own signature or content type was wrong, so a strict subscriber rejects the delivery.",
    ],
    fixes: [
      "Retry with exponential backoff and jitter, then disable the subscription after repeated failures.",
      "Include a unique event id and a timestamp so receivers can deduplicate.",
      "Give receivers a way to see and replay missed deliveries in a self-service portal.",
    ],
  },
  {
    id: "payment-gateway",
    title: "Payment gateway failure",
    category: "external-services",
    severity: "critical",
    languages: ["any"],
    patterns: [
      /payment (?:gateway|provider|declined|failed)/i,
      /card (?:declined|not supported)/i,
      /charge failed|chargeback/i,
      /psp|acquirer|stripe|paypal|braintree/i,
      /authorization (?:failed|declined)/i,
    ],
    reasons: [
      "The issuer declined the card (insufficient funds, fraud, do-not-honour).",
      "The gateway timed out after the charge was created, so the outcome is unknown.",
      "3-D Secure / SCA verification was not completed by the client.",
    ],
    fixes: [
      "Treat a timeout as an unknown outcome and reconcile with a status query before retrying.",
      "Make every payment operation idempotent with the gateway's idempotency key.",
      "Distinguish a customer-facing decline (400) from a gateway fault (retry, alert).",
    ],
  },

  // ------------------------------------------------------- container runtime
  {
    id: "oom-killed",
    title: "Container OOM-killed",
    category: "container-runtime",
    severity: "critical",
    languages: ["docker", "kubernetes", "any"],
    patterns: [
      /oom-?kill/i,
      /out of memory: killed/i,
      /exit code 137/i,
      /container was killed.*memory/i,
      /memory\.limit exceeded/i,
    ],
    reasons: [
      "The container's memory limit was hit and the kernel killed the process without a JVM-level OOM.",
      "The JVM heap plus native memory (metaspace, direct buffers) exceeds the container limit.",
      "The limit is simply too small for the workload after a growth in data volume.",
    ],
    fixes: [
      "Headroom rule: set `-XX:MaxRAMPercentage` and keep ~25% for metaspace, threads and buffers.",
      "Reduce the retained working set before raising the limit — the process will still grow back.",
      "Alert on memory working set, not only on restarts.",
    ],
  },
  {
    id: "crash-loop",
    title: "Crash loop / restart back-off",
    category: "container-runtime",
    severity: "critical",
    languages: ["kubernetes", "docker", "systemd"],
    patterns: [
      /back-?off (?:restarting|failed)/i,
      /crashloopbackoff/i,
      /restart(?:ing|ed) (?:container|pod)/i,
      /exited with (?:code|status) 1/i,
      /start request repeated too quickly/i,
      /container .*restart/i,
    ],
    reasons: [
      "The process exits immediately: bad config, missing secret, failed migration, port conflict.",
      "The health check never passes, so the platform kills a working process.",
      "The app needs more memory or CPU than the limits allow and is killed on startup.",
    ],
    fixes: [
      "Read the previous container's logs — the reason is in the log before the exit.",
      "Separate liveness (is it stuck?) from readiness (can it serve?) and give startup time.",
      "Validate configuration and secrets at startup so the failure is explicit.",
    ],
  },
  {
    id: "image-pull",
    title: "Image or dependency pull failure",
    category: "container-runtime",
    severity: "warning",
    languages: ["kubernetes", "docker", "any"],
    patterns: [
      /failed to pull image/i,
      /imagepullbackoff|errimagepull/i,
      /manifest (?:for|image) .*not found/i,
      /pull access denied/i,
      /unknown: manifest unknown/i,
      /repository does not exist/i,
    ],
    reasons: [
      "The tag was never published, or the registry was garbage-collected / the tag was deleted.",
      "The image is private and the pull secret is missing or was rotated.",
      "Rate limits on the registry were hit from the same shared account.",
    ],
    fixes: [
      "Pin images by digest so a moving tag cannot break a deploy.",
      "Keep the pull secret in sync with the registry and monitor its expiry.",
      "Use a pull-through cache or a mirror to survive registry rate limits.",
    ],
  },
  {
    id: "probe-failure",
    title: "Health / readiness probe failure",
    category: "container-runtime",
    severity: "warning",
    languages: ["kubernetes", "docker", "any"],
    patterns: [
      /liveness probe failed/i,
      /readiness probe failed/i,
      /probe timed out/i,
      /unhealthy\b/,
      /health check failed/i,
      /too many restarts/i,
    ],
    reasons: [
      "The probe checks a dependency, so a slow database marks every instance unhealthy at once.",
      "The probe path is cheaper in the report but more expensive at runtime (full data scan).",
      "The startup grace period is shorter than the application's warm-up.",
    ],
    fixes: [
      "Make liveness a shallow local check and readiness a dependency-aware check.",
      "Increase the startup probe delay/period so warm-up does not look like a hang.",
      "Never restart on a transient dependency failure; drain instead.",
    ],
  },
  {
    id: "resource-throttling",
    title: "CPU throttling / resource limit",
    category: "container-runtime",
    severity: "warning",
    languages: ["kubernetes", "docker", "any"],
    patterns: [
      /cfs throttl/i,
      /cpu (?:throttled|quota exceeded|limit exceeded)/i,
      /out of cpu/i,
      /resource (?:limit|quota) (?:exceeded|reached)/i,
      /too many open files.*limit/i,
      /ephemeral-storage/i,
    ],
    reasons: [
      "The CPU quota is set too low for the bursty part of the workload, so latency spikes.",
      "Requests and limits are unbalanced, causing scheduling churn and noisy neighbours.",
      "Ephemeral storage filled with logs or temp files.",
    ],
    fixes: [
      "Set requests from measured usage and leave headroom above the limit for bursts.",
      "Move spiky work out of the request path (queues) so the container sees a steady rate.",
      "Write logs to stdout or an external sink instead of the container filesystem.",
    ],
  },

  // ------------------------------------------------------------ business rules
  {
    id: "insufficient-balance",
    title: "Insufficient balance / quota",
    category: "business-rules",
    severity: "info",
    languages: ["any"],
    patterns: [
      /insufficient (?:funds|balance|quota|credit)/i,
      /balance (?:is )?too low/i,
      /limit exceeded/i,
      /exceeds (?:the )?(?:available )?limit/i,
      /not enough (?:funds|credit|balance)/i,
    ],
    reasons: [
      "The customer genuinely does not have the funds or the quota — this is expected traffic, not a fault.",
      "A reservation was never released, so the available amount is lower than it should be.",
      "Currency rounding makes the available amount slightly too small.",
    ],
    fixes: [
      "Return a clear, actionable error (not a 500) and tell the user what is missing.",
      "Release holds in a `finally` path so a failed payment does not freeze funds.",
      "Exclude this case from error-rate alerting: it is a business outcome, not an incident.",
    ],
  },
  {
    id: "inventory",
    title: "Stock / inventory conflict",
    category: "business-rules",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /out of stock/i,
      /insufficient stock/i,
      /inventory (?:conflict|mismatch|shortage)/i,
      /oversold|oversell/i,
      /sku .* not available/i,
      /no items? left/i,
    ],
    reasons: [
      "Two checkouts reserved the last item concurrently and both succeeded.",
      "Stock was not decremented atomically with the reservation.",
      "A third-party warehouse or ERP is the source of truth and is stale.",
    ],
    fixes: [
      "Reserve atomically (`UPDATE … SET stock = stock - 1 WHERE stock > 0`) and check the affected rows.",
      "Expire reservations automatically so abandoned checkouts release stock.",
      "Reconcile with the source of truth and alert when the gap exceeds a threshold.",
    ],
  },
  {
    id: "duplicate-submission",
    title: "Duplicate submission",
    category: "business-rules",
    severity: "warning",
    languages: ["any"],
    patterns: [
      /duplicate (?:submission|request|payment|order|key)/i,
      /already (?:exists|submitted|processed|created)/i,
      /idempotency key/i,
      /request (?:was )?already (?:handled|received)/i,
      /unique constraint.*(?:id|key)/i,
    ],
    reasons: [
      "The user double-clicked, the client retried after a timeout, or a proxy replayed the request.",
      "There is no idempotency key, so an identical payload is treated as new work.",
      "A message was redelivered by the broker after a consumer restart.",
    ],
    fixes: [
      "Accept an idempotency key and store the result, replaying it for a repeated request.",
      "Treat a duplicate as success in the response, not as an error.",
      "Disable the submit button optimistically and make retries safe.",
    ],
  },
  {
    id: "mandatory-field",
    title: "Mandatory field missing",
    category: "business-rules",
    severity: "info",
    languages: ["any"],
    patterns: [
      /field .* is required/i,
      /missing (?:required )?(?:field|value|parameter)/i,
      /must not be (?:null|empty|blank)/i,
      /is mandatory/i,
      /required property/i,
    ],
    reasons: [
      "A caller omitted a field that the model treats as mandatory.",
      "A nullable column became non-nullable in the schema without a migration of the producers.",
      "An optional field became required in a newer release of the API.",
    ],
    fixes: [
      "Validate at the edge and return every missing field at once, not one per request.",
      "Make the field nullable in the domain model if it genuinely is optional.",
      "Version the contract before tightening a required field.",
    ],
  },

  // ---------------------------------------------------------- encoding/locale
  {
    id: "unicode-error",
    title: "Unicode / character-set failure",
    category: "i18n-encoding",
    severity: "warning",
    languages: ["python", "java", "node", "go", "any"],
    patterns: [
      /unicode(encode|decode)?error/i,
      /charmap|codec can't (?:encode|decode)/i,
      /illegal byte sequence/i,
      /malformed (?:input|byte)/i,
      /unknown encoding/i,
      /too many bytes in/i,
    ],
    reasons: [
      "Text was written to a stream that expects UTF-8 with a platform default encoding.",
      "Input bytes are not valid UTF-8 (truncated upload, latin-1 source, wrong assumption).",
      "A fixed-size buffer was used for variable-length characters.",
    ],
    fixes: [
      "Be explicit about encodings everywhere; never rely on the platform default.",
      "Handle the decode error by rejecting the request with 400 instead of crashing.",
      "Read and write text with an explicit UTF-8 stream everywhere.",
    ],
  },
  {
    id: "timezone-missing",
    title: "Time-zone or clock conversion problem",
    category: "i18n-encoding",
    severity: "warning",
    languages: ["java", "python", "node", "go", "any"],
    patterns: [
      /nonexistent local time/i,
      /ambiguous local time/i,
      /zoneinfo|not a recognized timezone/i,
      /invalid time ?zone/i,
      /cannot (?:find|load) (?:the )?timezone/i,
      /localtime/i,
    ],
    reasons: [
      "A local time falls in the DST spring-forward gap or the autumn overlap.",
      "The process has no time-zone database installed (minimal container image).",
      "Naive local times are stored and later interpreted in a different zone.",
    ],
    fixes: [
      "Store and transport instants in UTC; convert to a zone only at the presentation edge.",
      "Install the tz database in the image and fail startup if it is missing.",
      "Use a zone id (`Europe/Paris`) instead of an abbreviation (`CEST`), which is ambiguous.",
    ],
  },
  {
    id: "locale-missing",
    title: "Missing locale or message bundle",
    category: "i18n-encoding",
    severity: "warning",
    languages: ["java", "python", "node", "any"],
    patterns: [
      /no message bundle|messages? not found for locale/i,
      /missing (?:translation|resource bundle)/i,
      /missinglocale|unsupportedlocale/i,
      /fallback to (?:en|en-us)/i,
      /key not found in (?:bundle|translations)/i,
    ],
    reasons: [
      "A new language was added without copying every key, so it silently falls back.",
      "The default locale is not bundled and the fallback produces raw keys for the user.",
      "Key names changed but one translation file was not updated.",
    ],
    fixes: [
      "Fail the build when a locale file is missing keys, rather than at request time.",
      "Make key naming mechanical (derived from the message id) so it cannot drift.",
      "Test that no key resolves to itself in any supported locale.",
    ],
  },

  // -------------------------------------------------------------- scheduling
  {
    id: "job-missed",
    title: "Scheduled job missed / did not run",
    category: "scheduling",
    severity: "warning",
    languages: ["cron", "quartz", "airflow", "node", "java"],
    patterns: [
      /missed (?:run|execution|fire)/i,
      /job .* did not run/i,
      /cron .*skipped/i,
      /misfire|misfired/i,
      /scheduler .* not (?:started|triggered)/i,
      /job was skipped/i,
    ],
    reasons: [
      "The scheduler was not running (restart, crash, autoscaler scaled to zero).",
      "The job is defined in several places and one instance won the leader election silently.",
      "The schedule expression is interpreted in the wrong time zone, so it fires at night.",
    ],
    fixes: [
      "Make the scheduler a singleton with a lease, and alert when no run has happened on time.",
      "Design jobs to be idempotent and resumable: a missed run must be catchable.",
      "Pin the time zone of the schedule explicitly and test it across a DST boundary.",
    ],
  },
  {
    id: "job-overlap",
    title: "Overlapping job runs",
    category: "scheduling",
    severity: "warning",
    languages: ["cron", "quartz", "airflow", "node", "java"],
    patterns: [
      /job .* still running|previous run .* still (?:running|in progress)/i,
      /overlapping (?:run|execution)/i,
      /concurrent execution (?:of|not allowed)/i,
      /already running/i,
      /skipping (?:this )?run/i,
    ],
    reasons: [
      "A job takes longer than its interval and the next run starts anyway.",
      "Several instances run the same job because the lock was not held (or expired mid-run).",
      "A manual trigger was fired while the scheduled run was in progress.",
    ],
    fixes: [
      "Guard with a lock/lease whose TTL exceeds the worst-case run time.",
      "Skip or queue overlapping runs instead of starting them, and log which policy applied.",
      "Alert when runtime approaches the interval — the overlap is a symptom of a slow job.",
    ],
  },
  {
    id: "job-stuck",
    title: "Stuck / hanging job",
    category: "scheduling",
    severity: "critical",
    languages: ["cron", "quartz", "airflow", "node", "java", "any"],
    patterns: [
      /job .* (?:hung|stuck|timed out)/i,
      /heartbeat (?:lost|missed)/i,
      /deadlock detected/i,
      /stuck for \d+/i,
      /no progress for \d+/i,
    ],
    reasons: [
      "The worker died without releasing the lock, so the job waits forever.",
      "The job is blocked on an external call with no timeout.",
      "Two jobs deadlocked each other over the same rows.",
    ],
    fixes: [
      "Put a timeout and a heartbeat on every job, and let the scheduler reclaim dead workers.",
      "Give every external call inside a job a deadline.",
      "Make jobs resumable so a restart continues instead of restarting from zero.",
    ],
  },
];